spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.43.41/ddmall_pms
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
         server-addr: 127.0.0.1:8848
  application:
    name: ddmall-product
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1  #1为已删除
      logic-not-delete-value: 0 #0为未删除
server:
  port: 11000